# https://aka.ms/yaml

jobs:
- job: test
  displayName: 'Lint & Build Test'

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: docker build -t pythondiscord/snekbox-ci:latest -f docker/ci.Dockerfile .
    displayName: 'Build CI Container'

- job: build
  displayName: 'Lint & Build Test'
  dependsOn: test
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - task: Docker@1
    displayName: 'Login: Docker Hub'

  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'DockerHub'
    command: 'login'

  steps:
  - script: docker build -t pythondiscord/snekbox:latest -f docker/Dockerfile .
    displayName: 'Build Final Image'

  - script: docker push pythondiscord/snekbox:latest
    displayName: 'Push Image to Dockerhub'
