version: '3'
services:
  pdrmq:
    hostname: "pdrmq"
    image: pythondiscord/rmq:latest
    expose:
      - "15672"
    ports:
       - "15672:15672"
    networks:
      - sneknet
    environment:
      RABBITMQ_DEFAULT_USER: rabbits
      RABBITMQ_DEFAULT_PASS: rabbits

  pdsnekbox:
    privileged: true
    hostname: "pdsnekbox"
    image: pythondiscord/snekbox:latest
    networks:
      - sneknet
    environment:
      RMQ_HOST: pdrmq
      RMQ_USERNAME: rabbits
      RMQ_PASSWORD: rabbits

  pdsnekboxweb:
    hostname: "pdsnekboxweb"
    image: pythondiscord/snekboxweb:latest
    networks:
      - sneknet
    ports:
       - "5000:5000"
    expose:
      - "5000"
    environment:
      RMQ_HOST: pdrmq
      RMQ_USERNAME: rabbits
      RMQ_PASSWORD: rabbits


networks:
  sneknet:
